spring:
  datasource:
    url: jdbc:mysql://localhost:3308/shopping_mall?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: team1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: disabled
      password: disabled

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} : %msg%n"
  file:
    encoding: UTF-8
  encoding:
    charset: UTF-8

jwt:
  secret: NxD@49#jKw!rMv7Up2zLt$gQpY%1fA3eTb8CkD$HzLwRm
